resources:    
  - name: vijay
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
        include: pipeline.*
      branches:  # optional
        include: master
        exclude: readme        
      tags:  # optional
        include: v.* 
      buildOn:  # optional
        commit: true
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
        tagCreate: true
      shallowDepth: 1  # optional 
      cloneProtocol: https      

  - name: gitres
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master 
        exclude: readme
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
#          tagCreate: false
      shallowDepth: 10  # optional 
      cloneProtocol: https      

  - name: gitpullcreatetrue
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master 
#         exclude: test
      buildOn:  # optional
         commit: false
         pullRequestCreate: true
#          releaseCreate: true
#          tagCreate: false
#       shallowDepth: 10  # optional 
      cloneProtocol: https

  - name: gitpullcreatefalse
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master
#         exclude: readme
      buildOn:  # optional
         commit: false
         pullRequestCreate: false
#          releaseCreate: true
#          tagCreate: false
      shallowDepth: 10  # optional 
      cloneProtocol: https      

  - name: gitpullclosetrue
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master
        exclude: readme
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
         pullRequestClose: true
#          releaseCreate: true
#          tagCreate: false
      shallowDepth: 20  # optional   
      cloneProtocol: https      

  - name: gitpullclosefalse
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master
        exclude: readme
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
         pullRequestClose: false
#          releaseCreate: true
#          tagCreate: false
      shallowDepth: 10  # optional     
      cloneProtocol: https      

  - name: gittagcreatetrue
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master
        exclude: readme
      tags:  # optional
        exclude: m.*      
        include: v.*         
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
#          pullRequestClose: false
#          releaseCreate: true
         tagCreate: true
      shallowDepth: 10  # optional   
      cloneProtocol: https      

  - name: gittagcreatefalse
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master
        exclude: readme
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
#          pullRequestClose: false
#          releaseCreate: 
         tagCreate: false
      shallowDepth: 10  # optional 
      cloneProtocol: https      

  - name: gitreleasecreatetrue
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master
        exclude: readme
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
#          pullRequestClose: false
         releaseCreate: true
#          tagCreate: true
      shallowDepth: 10  # optional   
      cloneProtocol: https      

  - name: gitreleasecreatefalse
    type: GitRepo
    configuration:
      gitProvider: s_git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master
        exclude: readme
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
#          pullRequestClose: false
         releaseCreate: false
#          tagCreate: false
      shallowDepth: 10  # optiona
      cloneProtocol: https      


pipelines:

  - name: pipelines_true
  
    steps:
      - name: s_BashTriggerTrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: vijay
        execution:
          onExecute:
            - printenv 
            - pushd $res_vijay_resourcePath
            - git log
            - ls
            - cat pipelines.sh    

  - name: pipelines_false
  
    steps:
      - name: s_BashTriggerFalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitres
        execution:
          onExecute:
            - printenv 
            - pushd $res_gitresource_resourcePath
            - git log
            - ls
            - cat pipelines.sh         
            
  - name: pipelines_Pullcreatetrue
    steps:
      - name: s_BashTriggercreatetrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitpullcreatetrue
        execution:              
          onExecute:
            - printenv     

  - name: pipelines_pullclosetrue
    steps:
      - name: s_BashTriggerclosetrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitpullclosetrue
        execution:              
          onExecute:
            - printenv 

  - name: pipelines_Pullcreatefalse
    steps:
      - name: s_BashTriggercreatefalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitpullcreatefalse
        execution:              
          onExecute:
            - printenv     

  - name: pipelines_pullclosefalse
    steps:
      - name: s_BashTriggerclosefalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitpullclosefalse
        execution:              
          onExecute:
            - printenv        

  - name: pipelines_tagcreatefalse
    steps:
      - name: s_Bashtagcreatefalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gittagcreatefalse
        execution:              
          onExecute:
            - printenv     

  - name: pipelines_tagcreatetrue
    steps:
      - name: s_Bashtagcreatetrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gittagcreatetrue
        execution:              
          onExecute:
            - printenv  

  - name: pipelines_releasecreatefalse
    steps:
      - name: s_Bashreleasecreatefalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitreleasecreatefalse
        execution:              
          onExecute:
            - printenv     

  - name: pipelines_releasecreatetrue
    steps:
      - name: s_Bashreleasecreatetrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitreleasecreatetrue
        execution:              
          onExecute:
            - printenv     


          
