resources:    
  - name: gittagcreatetrue
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/dummy
      files:  # optional
        exclude: readme
      branches:  # optional
        include: master
        exclude: readme
      tags:  # optional
        exclude: m.*      
        include: v.*         
      buildOn:  # optional
         commit: false
         tagCreate: true
      shallowDepth: 10  # optional     



pipelines:

  - name: pipelines_true
  
    steps:
      - name: s_Bashtagcreatetrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gittagcreatetrue
        execution:              
          onExecute:
            - printenv       
  
