resources:    
  - name: gittagcreatetrue
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/dummy     
      buildOn:  # optional
         tagCreate: true   



pipelines:

  - name: pipelines_true
  
    steps:
      - name: s_Bashtagcreatetrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gittagcreatetrue
        execution:              
          onExecute:
            - printenv       
  
